# .github/workflows/auto-index-architecture-docs.yml

name: Auto-Index Architecture Documents

on:
  pull_request:
    types: [closed]
    branches: [main]  # Adjust to your default branch
    paths: 
      - 'docs/**'  # Adjust path to your architecture docs folder
      - 'architecture/**'  # Add other paths as needed

jobs:
  auto-index-docs:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Install dependencies
      run: |
        npm init -y
        npm install glob typescript ts-node @types/node
    
    - name: Auto-index architecture documents
      env:
        DOCS_DIR: 'docs'  # Configure your docs directory here
      run: |
        npx ts-node .github/scripts/auto-index-docs.ts
    
    - name: Check for changes
      id: check_changes
      run: |
        if git diff --quiet; then
          echo "has_changes=false" >> $GITHUB_OUTPUT
        else
          echo "has_changes=true" >> $GITHUB_OUTPUT
        fi
    
    - name: Commit and push changes
      if: steps.check_changes.outputs.has_changes == 'true'
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        
        # Only add the docs directory and exclude npm/node files
        git add docs/
        # Add any other architecture directories if you have them
        # git add architecture/
        
        # Make sure we don't accidentally commit npm files
        git reset HEAD package*.json node_modules/ 2>/dev/null || true
        
        git commit -m "Auto-index architecture documents"
        git push
